// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9dfup0PidQlVnoghHeWJvqq5oY4X9R5U',
    appId: '1:270329901420:web:647318a5ab216899384349',
    messagingSenderId: '270329901420',
    projectId: 'mymapapplication-5590c',
    authDomain: 'mymapapplication-5590c.firebaseapp.com',
    storageBucket: 'mymapapplication-5590c.appspot.com',
    measurementId: 'G-W45D7S6PSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMdloqj5Kn4sUuqT__DflPhT8_TZm8Hhc',
    appId: '1:270329901420:android:ee899e6747364a15384349',
    messagingSenderId: '270329901420',
    projectId: 'mymapapplication-5590c',
    storageBucket: 'mymapapplication-5590c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvaopefK23Mk2qXjpOABQgVJVYvInzyeA',
    appId: '1:270329901420:ios:3e1a1e5c25e6d429384349',
    messagingSenderId: '270329901420',
    projectId: 'mymapapplication-5590c',
    storageBucket: 'mymapapplication-5590c.appspot.com',
    iosBundleId: 'com.example.mymapapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvaopefK23Mk2qXjpOABQgVJVYvInzyeA',
    appId: '1:270329901420:ios:ea913397c87afc27384349',
    messagingSenderId: '270329901420',
    projectId: 'mymapapplication-5590c',
    storageBucket: 'mymapapplication-5590c.appspot.com',
    iosBundleId: 'com.example.mymapapplication.RunnerTests',
  );
}
